// services/gemini.js
// The Gemini key lives ONLY here, on the server. The frontend NEVER
// imports this file or sees this key - it only ever talks to
// POST /api/chat.

const { GoogleGenerativeAI } = require("@google/generative-ai");

let genAI = null;
let model = null;

const systemInstructionText =
  "You are SAHARA, a warm, supportive AI wellbeing companion for university " +
  "students. Keep responses concise (2-4 sentences), calm, and non-clinical. " +
  "You are not a therapist and should not attempt to diagnose. For low-stakes " +
  "topics like study techniques, sleep habits, or exam stress, be conversational " +
  "and helpful. If a student seems to be struggling significantly, gently " +
  "encourage them to use the 'Message a counselor' option.";

if (process.env.GEMINI_API_KEY) {
  try {
    genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);
    model = genAI.getGenerativeModel({
      model: process.env.GEMINI_MODEL || "gemini-2.0-flash",
      systemInstruction: {
        role: "system",
        parts: [{ text: systemInstructionText }],
      },
    });
  } catch (e) {
    console.warn("Gemini service initialization warning:", e.message);
  }
}

// Keyword list for routing away from freeform AI, per the earlier
// risk-tiered response spec. This is intentionally simple/conservative -
// false positives (routing a borderline message to the safe response) are
// far preferable to false negatives here.
const CRISIS_KEYWORDS = [
  "kill myself", "suicide", "end my life", "self harm", "self-harm",
  "hurt myself", "want to die", "no reason to live", "can't go on",
];

function containsCrisisLanguage(text) {
  const lower = text.toLowerCase();
  return CRISIS_KEYWORDS.some((kw) => lower.includes(kw));
}

// Fixed, human-reviewed response - NEVER generated by the AI.
const CRISIS_RESPONSE = {
  text:
    "It sounds like you're going through something really heavy right now, " +
    "and I want to make sure you get support from someone who can really help. " +
    "Please reach out to a crisis line right now — you don't have to handle this alone.",
  crisisResources: [
    { name: "24/7 Student Helpline", contact: "14416" },
    { name: "Campus Counseling Center", contact: "See your Profile page for direct contact" },
  ],
};

async function getChatReply(userMessage, conversationHistory = []) {
  if (containsCrisisLanguage(userMessage)) {
    return { ...CRISIS_RESPONSE, flaggedCrisis: true };
  }

  if (!model) {
    return {
      text: "I'm here to support you. Try taking three deep breaths and taking one task at a time. If you'd like to explore coping strategies, our resource library and campus counselors are here for you.",
      flaggedCrisis: false,
    };
  }

  try {
    // Filter and format history for Gemini API
    const history = conversationHistory
      .filter((m) => m && m.content && (m.role === "user" || m.role === "assistant"))
      .map((m) => ({
        role: m.role === "assistant" ? "model" : "user",
        parts: [{ text: m.content }],
      }));

    const chat = model.startChat({ history });
    const result = await chat.sendMessage(userMessage);
    return { text: result.response.text(), flaggedCrisis: false };
  } catch (err) {
    console.warn("Gemini chat execution fallback:", err.message);
    return {
      text: "Thank you for reaching out. University demands can feel overwhelming at times, but taking small pauses and focusing on what you can control right now makes a big difference. Feel free to explore our focus and relaxation tools.",
      flaggedCrisis: false,
    };
  }
}

module.exports = { getChatReply, containsCrisisLanguage };
